### ISSUE TITLE
Socket.io Crashes on Client Disconnect

### ISSUE THREAD

**Issue by ROODAY** [philsiff/ChatAnon#6]
It seems to be an error originating from socket itself, as the stack trace is not pointing to anything in our code.

```
TypeError: Cannot convert null to object
    at Adapter.delAll (R:\Documents\GitHub\test\ChatAnon\node_modules\socket.io\node_modules\socket.io-adapter\index.js:86:33)
    at Socket.leaveAll (R:\Documents\GitHub\test\ChatAnon\node_modules\socket.io\lib\socket.js:261:16)
    at Socket.onclose (R:\Documents\GitHub\test\ChatAnon\node_modules\socket.io\lib\socket.js:412:8)
    at Client.onclose (R:\Documents\GitHub\test\ChatAnon\node_modules\socket.io\lib\client.js:230:12)
    at Socket.EventEmitter.emit (events.js:117:20)
    at Socket.onClose (R:\Documents\GitHub\test\ChatAnon\node_modules\socket.io\node_modules\engine.io\lib\socket.js:248:10)
    at WebSocket.g (events.js:180:16)
    at WebSocket.EventEmitter.emit (events.js:92:17)
    at WebSocket.Transport.onClose (R:\Documents\GitHub\test\ChatAnon\node_modules\socket.io\node_modules\engine.io\lib\transport.js:113:8)
    at WebSocket.g (events.js:180:16)
```

**Comment by ROODAY** [comment]
praise noah! basically replaced

```
var roomList = io.sockets.adapter.rooms;
connectclients.forEach(function(client){
    delete roomList[client];
});
socket.emit("roomList", Object.keys(roomList));
```

with

```
var roomList = [];
Object.keys(io.sockets.adapter.rooms).forEach(function(room) {
    var isclient = false;
    connectclients.forEach(function(client){
        if (room === client) {
            isclient = true;
        }
    });
    if (isclient === false) {
        roomList.push(room);
    }
});
socket.emit("roomList", roomList);
```
